# Generated by Django 5.2.6 on 2025-09-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=120)),
                ('metodoDePago', models.CharField(max_length=120)),
            ],
        ),
    ]
