# Generated by Django 5.2.6 on 2025-09-14 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='metodoDePago',
            new_name='metodo_de_pago',
        ),
    ]
