# Generated by Django 5.2.5 on 2025-09-16 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_metododepago_item_metodo_de_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=100)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='pedidos.item')),
            ],
        ),
    ]
